script: 
 - rm -Rf .git
 - rm -Rf wiki
 - rm -Rf release
 - cd ..
 - tar -cvzf  gt-dashboard.tar.gz gt-dashboard/ 


deploy:
  provider: releases
  api-key: "b0b2df462945c8a21b9bf077dc43d6afa50f5c2b"
  file: "gt-dashboard.tar.gz"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true