script:
  - cd ..
  - cp -R gt-dashboard build-dashboard
  - cd build-dashboard
  - rm -Rf .git
  - rm -Rf wiki
  - cd ..
  - tar -czf gt-dashboard.tar.gz build-dashboard
  - cd gt-dashboard

before_deploy: 
  - git fetch --tags
    
deploy:
  provider: releases
  api-key: "2291bcfba41488b6597037b248d7426b039c0b20"
  file: "../gt-dashboard.tar.gz"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
